*First Question:*


In [1]:
import numpy as np

# Global variables
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def basic_numpy_operations():
    global arr_1d, arr_2d

    print("1D Array:", arr_1d)
    print("2D Array:\n", arr_2d)

    print("Sum of 1D Array:", np.sum(arr_1d))
    print("Mean of 2D Array:", np.mean(arr_2d))
    print("Transpose of 2D Array:\n", arr_2d.T)

# Call the function
basic_numpy_operations()


1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of 1D Array: 15
Mean of 2D Array: 5.0
Transpose of 2D Array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


**SEcond Question**

In [2]:
import numpy as np

def image_processing():
    # Creating a grayscale image using a 2D NumPy array
    image = np.random.randint(0, 256, (5, 5), dtype=np.uint8)
    print("Original Image:\n", image)

    # Slicing a portion of the image
    cropped = image[1:4, 1:4]
    print("Cropped Section:\n", cropped)

    # Inverting colors
    inverted_image = 255 - image
    print("Inverted Image:\n", inverted_image)

# Call the function
image_processing()


Original Image:
 [[ 88  24 193 163 193]
 [ 53  48  39  84  35]
 [ 64  59  58 174 241]
 [154 174  67  66 159]
 [ 39  68  79 233 180]]
Cropped Section:
 [[ 48  39  84]
 [ 59  58 174]
 [174  67  66]]
Inverted Image:
 [[167 231  62  92  62]
 [202 207 216 171 220]
 [191 196 197  81  14]
 [101  81 188 189  96]
 [216 187 176  22  75]]


**Third Question**

In [3]:
import numpy as np
import cv2

def scale_image(image, scale_factor):
    scaling_matrix = np.array([[scale_factor, 0, 0],
                               [0, scale_factor, 0],
                               [0, 0, 1]])
    rows, cols = image.shape[:2]
    scaled_image = cv2.warpPerspective(image, scaling_matrix, (cols, rows))
    return scaled_image

def rotate_image(image, angle):
    rows, cols = image.shape[:2]
    rotation_matrix = cv2.getRotationMatrix2D((cols / 2, rows / 2), angle, 1)
    rotated_image = cv2.warpAffine(image, rotation_matrix, (cols, rows))
    return rotated_image

def translate_image(image, tx, ty):
    translation_matrix = np.array([[1, 0, tx],
                                   [0, 1, ty],
                                   [0, 0, 1]])
    rows, cols = image.shape[:2]
    translated_image = cv2.warpPerspective(image, translation_matrix, (cols, rows))
    return translated_image

def image_processing():
    image = cv2.imread('image.jpg')  # Use your own image
    print("Original Image Shape:", image.shape)

    scaled_image = scale_image(image, 1.5)
    rotated_image = rotate_image(image, 45)
    translated_image = translate_image(image, 50, 30)

    cv2.imshow('Original', image)
    cv2.imshow('Scaled', scaled_image)
    cv2.imshow('Rotated', rotated_image)
    cv2.imshow('Translated', translated_image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

# Call the function
image_processing()


AttributeError: 'NoneType' object has no attribute 'shape'

**Forth Question**

In [4]:
import numpy as np
import cv2

def scale_image(image, scale_factor):
    scaling_matrix = np.array([[scale_factor, 0, 0],
                               [0, scale_factor, 0],
                               [0, 0, 1]])
    rows, cols = image.shape[:2]
    scaled_image = cv2.warpPerspective(image, scaling_matrix, (cols, rows))
    return scaled_image

def rotate_image(image, angle):
    rows, cols = image.shape[:2]
    rotation_matrix = cv2.getRotationMatrix2D((cols / 2, rows / 2), angle, 1)
    rotated_image = cv2.warpAffine(image, rotation_matrix, (cols, rows))
    return rotated_image

def translate_image(image, tx, ty):
    translation_matrix = np.array([[1, 0, tx],
                                   [0, 1, ty],
                                   [0, 0, 1]])
    rows, cols = image.shape[:2]
    translated_image = cv2.warpPerspective(image, translation_matrix, (cols, rows))
    return translated_image

def detect_faces(image_path):
    image = cv2.imread(image_path)
    image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
    faces = face_cascade.detectMultiScale(image_gray, scaleFactor=1.1, minNeighbors=5)

    for (x, y, w, h) in faces:
        face_region = image[y:y+h, x:x+w]
        cv2.imshow('Face Region', face_region)

        eyes_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')
        eyes = eyes_cascade.detectMultiScale(face_region, scaleFactor=1.1, minNeighbors=5)
        for (ex, ey, ew, eh) in eyes:
            eye_region = face_region[ey:ey+eh, ex:ex+ew]
            cv2.imshow('Eye Region', eye_region)

    cv2.imshow('Detected Faces', image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

def image_processing():
    image_path = 'image.jpg'  # Use your own image
    image = cv2.imread(image_path)
    print("Original Image Shape:", image.shape)

    scaled_image = scale_image(image, 1.5)
    rotated_image = rotate_image(image, 45)
    translated_image = translate_image(image, 50, 30)

    cv2.imshow('Original', image)
    cv2.imshow('Scaled', scaled_image)
    cv2.imshow('Rotated', rotated_image)
    cv2.imshow('Translated', translated_image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

    detect_faces(image_path)

# Call the function
image_processing()


AttributeError: 'NoneType' object has no attribute 'shape'